version: "3.9"

services:
  backend:
    image: python:3.12-slim
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - OPNXT_PUBLIC_MODE=1
    command: >
      bash -lc "apt-get update && apt-get install -y --no-install-recommends pandoc && rm -rf /var/lib/apt/lists/* &&
      pip install --no-cache-dir -r requirements.txt &&
      uvicorn src.orchestrator.api.main:app --host 0.0.0.0 --port 8000 --reload"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health').read()"]
      interval: 10s
      timeout: 5s
      retries: 6

  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
      - NEXT_PUBLIC_PUBLIC_MODE=1
    depends_on:
      - backend
    command: >
      bash -lc "npm install && npm run dev"

# Usage:
#   docker compose up --build
# Then open http://localhost:3000/projects
