# Example settings for OPNXT
# Copy to settings.yaml and fill in values as needed.
openai:
  api_key: "${OPENAI_API_KEY}"
  base_url: "${OPENAI_BASE_URL:https://api.x.ai/v1}"

xai:
  # Preferred: set XAI_API_KEY for Grok
  api_key: "${XAI_API_KEY}"
  model: "${XAI_MODEL:grok-2-latest}"

app:
  name: "OPNXT SDLC and PMO Assistant"
  debug: true
