name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests (coverage gate ≥80% for src/orchestrator)
        run: |
          pytest -q --cov=src/orchestrator --cov-report=term-missing --cov-report=xml --cov-fail-under=80

      - name: Generate traceability map
        run: |
          python - << 'PY'
          from src.orchestrator.tools.traceability import generate_traceability_map
          p = generate_traceability_map()
          print(p)
          PY

      - name: Upload traceability map artifact
        uses: actions/upload-artifact@v4
        with:
          name: traceability-map
          path: reports/traceability-map.json
          if-no-files-found: warn
