name: Render PDFs from Markdown (manual only)

on:
  # Keep this workflow available for later; disable automatic triggers for the public app
  workflow_dispatch:

jobs:
  build-pdfs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Install wkhtmltopdf
        run: |
          sudo apt-get install -y wkhtmltopdf

      - name: Create output directory
        run: |
          mkdir -p docs/pdf

      - name: Render PDFs from docs/*.md
        shell: bash
        run: |
          set -euo pipefail
          CSS="templates/pandoc/style.css"
          shopt -s nullglob
          for f in docs/*.md; do
            base=$(basename "$f" .md)
            out="docs/pdf/${base}.pdf"
            echo "Rendering $f -> $out"
            pandoc -s "$f" -t html5 ${CSS:+-c "$CSS"} \
              --metadata title="$base" \
              --pdf-engine=wkhtmltopdf \
              -o "$out"
          done

      - name: Upload PDFs artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdlc-pdfs
          path: docs/pdf/*.pdf
          if-no-files-found: warn

      - name: Commit PDFs back to repo (optional)
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          if [ -n "$(git status --porcelain docs/pdf)" ]; then
            git config user.name "github-actions"
            git config user.email "github-actions@users.noreply.github.com"
            git add docs/pdf
            git commit -m "chore(ci): render PDFs from Markdown"
            git push
          else
            echo "No PDF changes to commit."
          fi

  build-pdfs-latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Pandoc and TeX Live (XeLaTeX)
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra lmodern

      - name: Create output directory
        run: |
          mkdir -p docs/pdf-latex

      - name: Render PDFs from docs/*.md with XeLaTeX
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob
          for f in docs/*.md; do
            base=$(basename "$f" .md)
            out="docs/pdf-latex/${base}.pdf"
            echo "Rendering (LaTeX) $f -> $out"
            pandoc -s "$f" \
              --metadata title="$base" \
              --pdf-engine=xelatex \
              -V geometry:margin=1in \
              -o "$out"
          done

      - name: Upload PDFs (LaTeX) artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdlc-pdfs-latex
          path: docs/pdf-latex/*.pdf
          if-no-files-found: warn

      - name: Commit LaTeX PDFs back to repo (optional)
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          if [ -n "$(git status --porcelain docs/pdf-latex)" ]; then
            git config user.name "github-actions"
            git config user.email "github-actions@users.noreply.github.com"
            git add docs/pdf-latex
            git commit -m "chore(ci): render PDFs from Markdown (LaTeX)"
            git push
          else
            echo "No LaTeX PDF changes to commit."
          fi
